# Generated by Django 6.0 on 2025-12-08 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('Entre', 'Entre'), ('Sorti', 'Sorti')], max_length=5)),
                ('quantite', models.PositiveBigIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produits', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.produits')),
            ],
        ),
    ]
