# Generated by Django 6.0 on 2026-03-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entre'), ('OUT', 'Sorti')], max_length=3),
        ),
    ]
