# Generated by Django 6.0 on 2026-03-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stock_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='movement_type',
            field=models.CharField(choices=[('OUT', 'Sorti'), ('IN', 'Entre')], max_length=3),
        ),
    ]
